CREATE TABLE PUESTOS(
    ID_PUESTO int NOT NULL,
    NOMBRE varchar(200) NOT NULL,
    NIVEL_AUTORIZACION int NOT NULL,
    CONSTRAINT pk_ID_PUESTO PRIMARY KEY (ID_PUESTO)
);

CREATE TABLE EMPLEADOS(
    ID_EMPLEADO int IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE varchar(100) NOT NULL,
    APELLIDO varchar(100) NOT NULL,
    ID_PUESTO int NOT NULL,
    SALARIO float NOT NULL,
    ESTA_ACTIVO bit NOT NULL,
    FECHA_ALTA date NOT NULL,
    FECHA_BAJA date,
    MAIL varchar(150),
    CONSTRAINT fk_ID_PUESTO_empleados FOREIGN KEY (ID_PUESTO) REFERENCES PUESTOS(ID_PUESTO)
);

INSERT INTO PUESTOS(ID_PUESTO, NOMBRE, NIVEL_AUTORIZACION) VALUES
    (1, 'Director', 3),
    (2, 'Gerente', 3),
    (5, 'Jefe de sector', 2),
    (4, 'Administrativo', 1),
    (3, 'Vendedor', 0),
    (6, 'Secretario', 2);

INSERT INTO EMPLEADOS(NOMBRE, APELLIDO, ID_PUESTO, SALARIO, ESTA_ACTIVO, FECHA_ALTA, FECHA_BAJA, MAIL) VALUES
    ('Leilani', 'Kinney', 1, 383946.80, 1, '1996-03-21', null, 'lkinney@gmail.com'),
    ('Igor', 'England', 5, 283558.85, 1, '2013-03-28', null, 'iengland@hotmail.com'),
    ('Maya', 'Brock', 3, 164546.09, 1, '1993-10-24', null, null),
    ('Hayden', 'Moss', 4, 211695.50, 0, '2012-06-07', '2015-02-19', 'hmoss@gmail.com'),
    ('Amal', 'Colon', 2, 388933.60, 1, '2019-09-23', null, null);


select * from EMPLEADOS;

select NOMBRE from PUESTOS;

select NOMBRE from EMPLEADOS where ESTA_ACTIVO = 1;

select NOMBRE,APELLIDO,SALARIO from EMPLEADOS where SALARIO > 200000.00;

select NOMBRE,APELLIDO,FECHA_ALTA from EMPLEADOS where FECHA_ALTA <= '2012-06-07';

select NOMBRE,APELLIDO,MAIL from EMPLEADOS where MAIL is null;

select NOMBRE,APELLIDO,MAIL from EMPLEADOS where MAIL is not null;

select NOMBRE,APELLIDO,MAIL from EMPLEADOS where MAIL like '%gmail%';

select NOMBRE,APELLIDO from EMPLEADOS where APELLIDO like 'B%'

select NOMBRE,APELLIDO,ESTA_ACTIVO,SALARIO from EMPLEADOS where ESTA_ACTIVO = 1 AND SALARIO > 300000.00; 

select NOMBRE,APELLIDO,ESTA_ACTIVO,MAIL from EMPLEADOS where ESTA_ACTIVO = 0 OR MAIL is null; 

select NOMBRE, MAIL from EMPLEADOS where MAIL is not null AND NOMBRE like '%a%'; 

select NOMBRE,SALARIO,FECHA_ALTA from EMPLEADOS where (SALARIO >= 250000.00 AND FECHA_ALTA > '2000-12-12') OR (SALARIO < 250000.00 AND FECHA_ALTA < '2000-01-01');

select NOMBRE,SALARIO from EMPLEADOS where SALARIO between 100000.00 AND 250000.00;

select NOMBRE,SALARIO from EMPLEADOS where SALARIO not between 100000.00 AND 250000.00;

select NOMBRE,NIVEL_AUTORIZACION from PUESTOS where NIVEL_AUTORIZACION in (0,1,2);

select NOMBRE,NIVEL_AUTORIZACION from PUESTOS where NIVEL_AUTORIZACION not in (0,1,2);

select APELLIDO,NOMBRE from EMPLEADOS order by apellido;

select top(3) NOMBRE,APELLIDO,FECHA_ALTA from EMPLEADOS order by FECHA_ALTA;

select top(3) NOMBRE,APELLIDO,SALARIO from EMPLEADOS order by SALARIO desc;

select * from EMPLEADOS order by SALARIO desc;

select distinct NIVEL_AUTORIZACION from PUESTOS order by NIVEL_AUTORIZACION;

select EMPLEADOS.NOMBRE,PUESTOS.NOMBRE from EMPLEADOS INNER JOIN PUESTOS on EMPLEADOS.ID_PUESTO = PUESTOS.ID_PUESTO; 

select EMPLEADOS.NOMBRE,PUESTOS.NIVEL_AUTORIZACION from EMPLEADOS INNER JOIN PUESTOS on EMPLEADOS.ID_PUESTO = PUESTOS.ID_PUESTO AND PUESTOS.NIVEL_AUTORIZACION = 3;

select EMPLEADOS.APELLIDO,PUESTOS.NOMBRE from EMPLEADOS INNER JOIN PUESTOS on EMPLEADOS.ID_PUESTO = PUESTOS.ID_PUESTO order by EMPLEADOS.APELLIDO; 

select PUESTOS.NOMBRE,EMPLEADOS.APELLIDO from EMPLEADOS INNER JOIN PUESTOS on EMPLEADOS.ID_PUESTO = PUESTOS.ID_PUESTO order by PUESTOS.NOMBRE;

select EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, PUESTOS.NOMBRE, EMPLEADOS.ESTA_ACTIVO, PUESTOS.NIVEL_AUTORIZACION from EMPLEADOS INNER JOIN PUESTOS on EMPLEADOS.ID_PUESTO = PUESTOS.ID_PUESTO 
where EMPLEADOS.ESTA_ACTIVO = 1 order by PUESTOS.NIVEL_AUTORIZACION;

select NOMBRE from PUESTOS where ID_PUESTO not in (select ID_PUESTO from EMPLEADOS);

select NOMBRE from PUESTOS where ID_PUESTO in (select ID_PUESTO from EMPLEADOS);

select AVG(SALARIO) from EMPLEADOS where ESTA_ACTIVO = 1;

select SUM(SALARIO) from EMPLEADOS where ESTA_ACTIVO = 1;

select COUNT(*) from EMPLEADOS where SALARIO > 250000.00;

select COUNT(*) from EMPLEADOS where FECHA_ALTA < '2010-01-01';

select MAX(SALARIO) from EMPLEADOS;

select NOMBRE, NIVEL_AUTORIZACION from PUESTOS where NIVEL_AUTORIZACION = (select MIN(NIVEL_AUTORIZACION) from PUESTOS);

select CONCAT(NOMBRE, ' ' , APELLIDO) as NOMBRE_COMPLETO from EMPLEADOS;

select CONCAT(EMPLEADOS.NOMBRE, ' ', EMPLEADOS.APELLIDO) as NOMBRE_COMPLETO, PUESTOS.NOMBRE, PUESTOS.NIVEL_AUTORIZACION
from EMPLEADOS INNER JOIN PUESTOS on EMPLEADOS.ID_PUESTO = PUESTOS.ID_PUESTO AND NOMBRE from PUESTOS where ID_PUESTO not in (select ID_PUESTO from EMPLEADOS); 

SELECT CONCAT(E.NOMBRE, ' ', E.APELLIDO) AS NOMBRE_COMPLETO, P.NOMBRE AS NOMBRE_PUESTO, P.NIVEL_AUTORIZACION FROM EMPLEADOS E INNER JOIN
PUESTOS P ON E.ID_PUESTO = P.ID_PUESTO
UNION ALL
SELECT NULL AS NOMBRE_COMPLETO, P.NOMBRE AS NOMBRE_PUESTO, P.NIVEL_AUTORIZACION FROM PUESTOS P WHERE P.ID_PUESTO NOT IN (SELECT DISTINCT ID_PUESTO FROM EMPLEADOS);

select PUESTOS.NOMBRE, COUNT(EMPLEADOS.ID_EMPLEADO) as CANTIDAD_EMPLEADOS from PUESTOS LEFT JOIN EMPLEADOS on PUESTOS.ID_PUESTO = EMPLEADOS.ID_PUESTO
group by PUESTOS.NOMBRE order by CANTIDAD_EMPLEADOS;

select PUESTOS.NOMBRE, AVG(EMPLEADOS.SALARIO) as PROMEDIO_SALARIO from PUESTOS LEFT JOIN EMPLEADOS on PUESTOS.ID_PUESTO = EMPLEADOS.ID_PUESTO
group by PUESTOS.NOMBRE order by PROMEDIO_SALARIO;

select NOMBRE, APELLIDO, SALARIO from EMPLEADOS where SALARIO = (select MAX(SALARIO) from EMPLEADOS);

select EMPLEADOS.NOMBRE, PUESTOS.NIVEL_AUTORIZACION from EMPLEADOS INNER JOIN PUESTOS on EMPLEADOS.ID_PUESTO = PUESTOS.ID_PUESTO where
NIVEL_AUTORIZACION = (select MAX(NIVEL_AUTORIZACION) from PUESTOS); 

select * from EMPLEADOS where FECHA_ALTA = (select MIN(FECHA_ALTA) from EMPLEADOS);

select SALARIO from EMPLEADOS where SALARIO > (select AVG(SALARIO) from EMPLEADOS);

select COUNT(*) from EMPLEADOS where SALARIO > (select AVG(SALARIO) from EMPLEADOS);

update EMPLEADOS set MAIL = 'mbrock@yahoo.com' where ID_EMPLEADO = 3; 

update EMPLEADOS set ID_PUESTO = 4, SALARIO = 210000.00 where ID_EMPLEADO = 3; 

update EMPLEADOS set SALARIO = SALARIO + (SALARIO*25/100) where SALARIO < 250000.00;

update EMPLEADOS set FECHA_BAJA = GETDATE(), ESTA_ACTIVO = 0 where ID_EMPLEADO = 1;

delete from EMPLEADOS where ESTA_ACTIVO = 0;

select * from EMPLEADOS;	
